default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: s3_upload_development
  username: test
  password: test

test:
  <<: *default
  database: s3_upload_test
  username: test
  password: test

production:
  <<: *default
  database: s3_upload_production
  username: test
  password: test
